my_string = input('Привет! ')
количество = int(input('Введите количество символов введенного текста: '))
print('Ваш ответ:', количество)

name = input('Напишите слово My string! ')
print(name.upper())
print(name.lower())
print(name.replace(' ', ''))
print(name[0])
print(name[-1])
